version: 2
jobs:
  build:
    working_directory: ~/phrassed
    docker:
      - image: circleci/node:12
      - image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: terms-test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: install-yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: "Linting"
          command: yarn lint:ci
      - run:
          name: "Run Tests"
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
