version: 2
jobs:
  build:
    working_directory: ~/phrassed
    docker:
      - image: circleci/node:lts
      - image: postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: terms
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Linting"
          command: yarn lint:ci
      - run:
          name: "Run Unit Tests"
          command: yarn test:unit --ci
      - run:
          name: "Run Integration Tests"
          command: yarn test:integration
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
